name: bump_version
on:
  push
  # workflow_dispatch:
  #   inputs:
  #     version: 
  #       default: ""
  #       required: true
  #       description: "unprefixed version number (ex: '1.14.2')"
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure git
        run: |
          git config --global user.email "bot@coder.com"
          git config --global user.name "Coder Bot"
          git remote add github "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      - run: |
          ./ci/scripts/bump-coder-cli.sh 1.14.1
          git diff
          git checkout -b bump-coder-cli-1.14.1
          git add coder-cli.rb
          git commit -m "feat: bump coder-cli version to v$version"
          git push --set-upstream github bump-coder-cli-1.14.1
          gh pr create --fill --reviewer cmoog
