name: bump_version
on:
  workflow_dispatch:
    inputs:
      version: 
        default: ""
        required: true
        description: "unprefixed version number (ex: '1.14.2')"
jobs:
  coder-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Open PR to bump coder-cli version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            ./ci/scripts/bump-coder-cli.sh ${{ github.event.inputs.version }}
            git diff
            git checkout -b bump-coder-cli-${{ github.event.inputs.version }}
            git add coder-cli.rb
            git commit -m "feat: bump coder-cli version to v${{ github.event.inputs.version }}"
            git push --set-upstream origin bump-coder-cli-${{ github.event.inputs.version }}
            gh pr create \
              --title="bump coder-cli version to v${{ github.event.inputs.version }}" \
              --body="" \
              --reviewer cmoog
